### PR TITLE
Support also B2B/COR1 payments (instead of only CORE)

### PR DESCRIPTION
**Pull request by mdornseif**
I tried to also extend the tests but since there is no documentation on how to run them I did not test the tests ;-)

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi! :) Thank you!

> I tried to also extend the tests but since there is no documentation on how to run them I did not test the tests ;-)
You can run them like this:

    pip install -r requirements_dev.txt
    py.test tests

**Comment by raphaelm** [comment]
Would you mind *splitting* the test such that there is one test using CORE and one using B2B?

**Comment by mdornseif** [comment]
Sure. I hope this is what you had in mind.

**Comment by raphaelm** [comment]
Yep, looks good. Only issue:
> ERROR: /home/travis/build/raphaelm/python-sepadd/tests/test_00800302_b2b.py Imports are incorrectly sorted.

Could you run ``isort -rc .`` to fix that automatically? :)

**Comment by mdornseif** [comment]
sigh. … disable Sublime Fix Imports … find isort … understand isort (ah, `-sl` is the way it's formated here) … install isort … excute, comit, push

… feels like contributing to Mozilla.

**Comment by raphaelm** [comment]
> sigh. … disable Sublime Fix Imports … find isort … understand isort (ah, -sl is the way it's formated here) … install isort … excute, comit, push

Sorry you had this experience :\ I'll try to improve on documentation. However, ``-sl`` shouldn't have been required since travis just checks with ``isort -rc -c sepadd tests``, so with no special configuration.

**Comment by raphaelm** [comment]
Thanks! :)

**Pull request merged**
